#include "streamer_rf/transport.hpp"
#include "streamer_rf/poisson.hpp"
#include "streamer_rf/sp3.hpp"
#include <petscsys.h>
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <tuple>
#include <vector>
using namespace streamer_rf;
namespace fs=std::filesystem;
namespace {constexpr double pi=3.14159265358979323846;
void transport(const fs::path&root){fs::create_directories(root);std::ofstream f(root/"face_flux_sweep.csv");f<<"n_left,n_right,w_left,w_right,diffusion,h,epsilon,n_ref,sg_flux,isg_flux,branch\n"<<std::setprecision(17);for(double h:{.01,.005})for(double grad:{1.,10.,100.,1000.,10000.})for(double ratio:{.1,1.,10.,1e3}){double nl=1e6,nr=nl*ratio,wl=-grad/2,wr=grad/2;IsgDiagnostics d;f<<nl<<','<<nr<<','<<wl<<','<<wr<<",1,"<<h<<",0.01,1000000,"<<sg_flux(nl,nr,0,1,h)<<','<<isg0_flux(nl,nr,wl,wr,1,h,.01,1e6,&d)<<','<<d.branch<<'\n';}
 std::ofstream c(root/"conservation.csv");c<<"nodes,steps,cfl,initial_mass,final_mass,relative_mass_error,min_density,max_density\n";for(int N:{100,200})for(double cfl:{.1,.2,.4}){std::vector<double>n(N),flux(N);for(int i=0;i<N;++i)n[i]=1e6*(1+.2*std::sin(2*pi*(i+.5)/N));const double dx=1.0/N,m0=std::accumulate(n.begin(),n.end(),0.0),dt=cfl*std::min(dx/.1,dx*dx/(2*.01));for(int step=0;step<200;++step){for(int i=0;i<N;++i){int q=(i+1)%N;flux[i]=sg_flux(n[i],n[q],.1,.01,dx);}std::vector<double>nn(n);for(int i=0;i<N;++i)nn[i]-=dt/dx*(flux[i]-flux[(i+N-1)%N]);n.swap(nn);}double m=std::accumulate(n.begin(),n.end(),0.0);c<<N<<",200,"<<cfl<<','<<m0<<','<<m<<','<<std::abs(m-m0)/m0<<','<<*std::min_element(n.begin(),n.end())<<','<<*std::max_element(n.begin(),n.end())<<'\n';}}
double l2(const ScalarField2D&a,const ScalarField2D&b){double e=0,n=0;for(std::size_t k=0;k<a.values().size();++k){e+=(a.values()[k]-b.values()[k])*(a.values()[k]-b.values()[k]);n+=b.values()[k]*b.values()[k];}return std::sqrt(e/std::max(n,1e-300));}
void poisson(const fs::path&root){fs::create_directories(root);std::ofstream mf(root/"manufactured_solution_errors.csv");mf<<"nr,nz,dr,dz,l2_error\n"<<std::setprecision(17);for(int nr:{17,33,65}){int nz=2*nr-1;AxisymmetricGrid g(nr,nz,1,-1,1);ScalarField2D ex(g),rhs(g),sol(g);for(int j=0;j<nz;++j)for(int i=0;i<nr;++i){double r=g.r(i),z=g.z(j);ex(i,j)=r*r*r*r+z*z*z*z;rhs(i,j)=16*r*r+12*z*z;}solve_axisymmetric_dirichlet(rhs,ex,sol,0);mf<<nr<<','<<nz<<','<<g.dr()<<','<<g.dz()<<','<<l2(sol,ex)<<'\n';}
 AxisymmetricGrid g(24,48,.02,-.02,.02);ScalarField2D rho(g);rho(6,24)=1e-9;OpenBoundaryOptions center{RingQuadratureMode::CellCenterRing,0};auto bc=open_charge_boundary(rho,center);double q=rho(6,24)*g.cell_volume(6);std::ofstream rr(root/"ring_charge_raw.csv");rr<<"case,charge_C,source_radius_m,observation_radius_m,axial_separation_m,computed_V\n";for(auto [name,I,J]:{std::tuple{"axis",0,0},std::tuple{"off_axis",23,24}})rr<<name<<','<<std::setprecision(17)<<q<<','<<g.r(6)<<','<<g.r(I)<<','<<g.z(J)-g.z(24)<<','<<bc(I,J)<<'\n';
 ScalarField2D gaussian(g);for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)gaussian(i,j)=1e-6*std::exp(-(g.r(i)*g.r(i)+g.z(j)*g.z(j))/(2*.003*.003));std::ofstream gb(root/"gaussian_boundary_raw.csv");gb<<"i,j,R,Z,rho,boundary_phi\n";auto exact=open_charge_boundary(gaussian,{RingQuadratureMode::GaussianCellQuadrature,0});for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)gb<<i<<','<<j<<','<<g.r(i)<<','<<g.z(j)<<','<<gaussian(i,j)<<','<<exact(i,j)<<'\n';
 std::ofstream ts(root/"open_boundary_threshold_sweep.csv");ts<<"eta,max_relative_boundary_difference\n";for(double eta:{0.,1e-4,1e-3,1e-2}){auto x=open_charge_boundary(gaussian,{RingQuadratureMode::GaussianCellQuadrature,eta});double e=0,n=0;for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)if(i==g.nr()-1||j==0||j==g.nz()-1){e=std::max(e,std::abs(x(i,j)-exact(i,j)));n=std::max(n,std::abs(exact(i,j)));}ts<<eta<<','<<e/n<<'\n';}
 PoissonBoundaryConfig pbc; pbc.r_outer.kind=pbc.z_lower.kind=pbc.z_upper.kind=BoundaryKind::OpenCharge;ScalarField2D p1(g),p2(g);solve_potential(gaussian,0,pbc,p1);
 std::ofstream gr(root/"gauss_law_residual.csv");gr<<"relative_discrete_residual\n";double re=0,rn=0;for(int j=1;j<g.nz()-1;++j)for(int i=0;i<g.nr()-1;++i){double r=g.r(i),rp=g.radial_face(i+1),rm=g.radial_face(i),ar=rp/(r*g.dr()*g.dr()),al=rm/(r*g.dr()*g.dr()),az=1/(g.dz()*g.dz());double lap=ar*(p1(i+1,j)-p1(i,j))+az*(p1(i,j+1)-2*p1(i,j)+p1(i,j-1));if(i>0)lap+=al*(p1(i-1,j)-p1(i,j));double target=-gaussian(i,j)/8.8541878128e-12;re+=(lap-target)*(lap-target);rn+=target*target;}gr<<std::sqrt(re/rn)<<'\n';
 gaussian(10,20)*=2;solve_potential(gaussian,0,pbc,p2);std::ofstream up(root/"boundary_update.csv");up<<"max_solution_change\n";double change=0;for(std::size_t k=0;k<g.size();++k)change=std::max(change,std::abs(p2.values()[k]-p1.values()[k]));up<<change<<'\n';}
void sp3(const fs::path&root){fs::create_directories(root);AxisymmetricGrid g(40,80,.002,-.002,.002);PoissonBoundaryConfig bc;SolverTolerances tight{1e-12,1e-16,10000};std::ofstream di(root/"boundary_iteration.csv");di<<"boundary_rtol,group,iterations,initial_residual,final_residual,converged,sph_change\n";for(double tol:{1e-6,1e-8,1e-10}){std::cout<<"SP3 tolerance "<<tol<<std::endl;ScalarField2D src(g),sph(g);for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)src(i,j)=1e20*std::exp(-(g.r(i)*g.r(i)+g.z(j)*g.z(j))/(2*.0004*.0004));std::array<Sp3GroupDiagnostics,3>d;Sp3BoundaryOptions bo;bo.rtol=tol;solve_photoionization(src,{},bc,sph,tight,bo,&d);for(int k=0;k<3;++k)di<<tol<<','<<k+1<<','<<d[k].iterations<<','<<d[k].initial_residual<<','<<d[k].final_residual<<','<<d[k].converged<<','<<d[k].sph_change<<'\n';}
 std::ofstream rm(root/"robin_manufactured.csv");rm<<"nr,nz,l2_error\n";for(int nr:{17,33,65}){int nz=2*nr-1;AxisymmetricGrid mg(nr,nz,1,-1,1);ScalarField2D ex(mg),rhs(mg),partner(mg),num(mg);double shift=2,c=.4,a=.7,cross=.3;for(int j=0;j<nz;++j)for(int i=0;i<nr;++i){ex(i,j)=std::exp(c*mg.z(j));rhs(i,j)=(c*c-shift)*ex(i,j);if(i==nr-1)partner(i,j)=-a*ex(i,j)/cross;if(j==0)partner(i,j)=(-a+c)*ex(i,j)/cross;if(j==nz-1)partner(i,j)=(-a-c)*ex(i,j)/cross;}solve_axisymmetric_robin(rhs,num,shift,a,cross,partner,tight);rm<<nr<<','<<nz<<','<<l2(num,ex)<<'\n';}
 std::ofstream fields(root/"gaussian_fields.csv");fields<<"case,i,j,r,z,emission,sp3_robin,sp3_dirichlet\n"<<std::setprecision(17);for(auto [name,sigma]:{std::pair{"narrow",.0002},std::pair{"medium",.0004},std::pair{"wide",.0006}}){std::cout<<"SP3 case "<<name<<std::endl;ScalarField2D src(g),rob(g),dir(g);for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)src(i,j)=1e20*std::exp(-(g.r(i)*g.r(i)+g.z(j)*g.z(j))/(2*sigma*sigma));solve_photoionization(src,{},bc,rob,tight);Sp3BoundaryOptions bo;bo.zero_dirichlet=true;solve_photoionization(src,{},bc,dir,tight,bo);for(int j=0;j<g.nz();++j)for(int i=0;i<g.nr();++i)fields<<name<<','<<i<<','<<j<<','<<g.r(i)<<','<<g.z(j)<<','<<src(i,j)<<','<<rob(i,j)<<','<<dir(i,j)<<'\n';}}
}
int main(int argc,char**argv){PetscInitialize(&argc,&argv,nullptr,nullptr);int rank;MPI_Comm_rank(PETSC_COMM_WORLD,&rank);fs::path root=argc>1?argv[1]:"results/stage2";transport(root/"wp2_1_isg0/data");poisson(root/"wp2_2_poisson");sp3(root/"wp2_3_sp3");if(rank==0)std::cout<<"stage2_measure completed output="<<root<<'\n';PetscFinalize();}
